import {
  Moon,
  SunMedium,
  Laptop,
  type LucideIcon,
  MapPin,
  Users,
  Clock,
  Edit,
  Trash,
  PlusCircle,
  ChevronDown,
  MoreHorizontal,
  ArrowUpDown,
  Eye,
  Martini,
  Building,
  Loader2,
  ExternalLink,
  Search,
  X,
  AlertTriangle,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  mapPin: MapPin,
  users: Users,
  clock: Clock,
  edit: Edit,
  trash: Trash,
  add: PlusCircle,
  chevronDown: ChevronDown,
  moreHorizontal: MoreHorizontal,
  arrowUpDown: ArrowUpDown,
  view: Eye,
  martini: Martini,
  building: Building,
  logo: Martini, // Example logo
  spinner: Loader2,
  externalLink: ExternalLink,
  search: Search,
  close: X,
  warning: AlertTriangle,
}
