
import {
  Moon,
  SunMedium,
  Laptop,
  type LucideIcon,
  MapPin,
  Users,
  Clock,
  Edit,
  Trash,
  PlusCircle,
  ChevronDown,
  MoreHorizontal,
  ArrowUpDown,
  Eye,
  Martini,
  Building,
  Loader2,
  ExternalLink,
  Search,
  X,
  AlertTriangle,
  Smartphone,
  Activity,
  PartyPopper,
  CheckCircle2,
  ShieldCheck,
  Facebook,
  Twitter,
  Instagram,
  Linkedin,
  Download,
  BarChart,
  Navigation,
} from "lucide-react"

export type Icon = LucideIcon

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  mapPin: MapPin,
  users: Users,
  clock: Clock,
  edit: Edit,
  trash: Trash,
  add: PlusCircle,
  chevronDown: ChevronDown,
  moreHorizontal: MoreHorizontal,
  arrowUpDown: ArrowUpDown,
  view: Eye,
  martini: Martini, // Also used as logo in landing page CTA
  building: Building,
  logo: Martini, 
  spinner: Loader2,
  externalLink: ExternalLink,
  search: Search,
  close: X,
  warning: AlertTriangle,
  smartphone: Smartphone,
  activity: Activity,
  partyPopper: PartyPopper,
  checkCircle2: CheckCircle2,
  shieldCheck: ShieldCheck,
  facebook: Facebook,
  twitter: Twitter,
  instagram: Instagram,
  linkedin: Linkedin,
  download: Download,
  barChart: BarChart,
  navigation: Navigation,
}
